### ISSUE TITLE
[CHORE] Project 초기 Setting

### ISSUE THREAD

**Issue by hansh0101** [TeamBeMyPlan/BeMyPlan-Android#1]
## 📌  Feature Issue

Project 초기 Setting

## 📝  To-do

- [x] Android Studio gradle 기초 setting
- [x] Kakao Map 연동
- [x] 패키지 구조 정리
