### ISSUE TITLE
[FEAT] 홈 뷰 레이아웃

### ISSUE THREAD

**Issue by briandr97** [TeamBeMyPlan/BeMyPlan-Android#10]
## 📌  Feature Issue
HomeFragment 레이아웃

## 📝  To-do
- [x] 로고 및 상단바 제작
- [x] 인기 여행 일정 (뷰페이저2)
- [x] 최신 여행 일정 (리사이클러뷰)
- [x] 에디터 추천 여행 일정 (리사이클러뷰)
- [ ] 인디케이터 추가해보기

## 📆 Date
0108 시작
0108 마감
