### ISSUE TITLE
[FEAT] 마이플랜 로그아웃 상태 레이아웃 제작

### ISSUE THREAD

**Issue by shb03323** [TeamBeMyPlan/BeMyPlan-Android#128]
## 📌  Feature Issue

로그아웃 상태의 마이플랜 뷰 제작

## 📝  To-do

- [x] 레이아웃 파일 생성
- [x] settings 클릭 영역 조정
- [x] withdrawal 클릭 영역 조정

## 📆 Date

0121~0121
