### ISSUE TITLE
[FEAT] 코드 리팩토링

### ISSUE THREAD

**Issue by hansh0101** [TeamBeMyPlan/BeMyPlan-Android#164]
## 📌  Feature Issue

[FEAT] 코드 리팩토링

## 📝  To-do

- [x] Fragment 생명주기 관련 리팩토링
- [x] RecyclerView Adapter 관련 리팩토링
- [x] ViewModel 관련 리팩토링
- [x] Coroutine Error Handling 관련 리팩토링

## 📆 Date

0124~0126
