### ISSUE TITLE
[FEAT] 구매 후 뷰 리사이클러뷰 구현

### ISSUE THREAD

**Issue by shb03323** [TeamBeMyPlan/BeMyPlan-Android#17]
## 📝  To-do

- [x] 두개의 리사이클러뷰를 하나의 어댑터로 연결
- [x] 리사이클러뷰 list item 구현
- [x] 모든 값들 data binding
- [x] image glide

## 📆 Date

0111 ~ 0112
