### ISSUE TITLE
[FEAT] 여행지 뷰 구현

### ISSUE THREAD

**Issue by briandr97** [TeamBeMyPlan/BeMyPlan-Android#20]
## 📌  Feature Issue
여행지 뷰 레이아웃을 구현한다.

## 📝  To-do
- [x] 상단 로고 바 제작
- [x] 리사이클러뷰(그리드) 제작
- [x] 잠금 아이콘과 그에 따른 밝기변화 구현

## 📆 Date
시작일: 0111
마감일: 0112

**Comment by briandr97** [comment]
마감일 지켜서 완료!!
