### ISSUE TITLE
[FEAT] 스크랩 기능 서버연결

### ISSUE THREAD

**Issue by hansh0101** [TeamBeMyPlan/BeMyPlan-Android#200]
## 📌  Feature Issue

[FEAT] 스크랩 기능 서버연결

## 📝  To-do

- [x] 구매 전 여행일정 컨텐츠 뷰 스크랩 기능 서버연결
- [x] 스크랩 뷰 스크랩 기능 서버연결
- [x] 리스트 뷰 스크랩 기능 서버연결

## 📆 Date

0223~0224
