### ISSUE TITLE
[REFACTOR] 서버통신 결과 처리 및 RecyclerView Adapter 관련 코드 리팩토링

### ISSUE THREAD

**Issue by hansh0101** [TeamBeMyPlan/BeMyPlan-Android#220]
## 📌  Feature Issue

[REFACTOR] 서버통신 코드 리팩토링 및 RecyclerView Adapter 관련 코드 리팩토링

## 📝  To-do

- [x] 서버통신 결과가 기존 ViewModel이 가지고 있던 LiveData 값과 같을 시 setValue하지 않도록 코드 리팩토링
- [x] 기존 try catch의 서버통신 코드 runCatching으로 변경
- [x] RecyclerView item 업데이트하는 코드 리팩토링

## 📆 Date

0302~0303
