### ISSUE TITLE
[FEAT] 홈 뷰 서버 연결

### ISSUE THREAD

**Issue by briandr97** [TeamBeMyPlan/BeMyPlan-Android#257]
## 📌  Feature Issue
홈 뷰 서버 연결

## 📝  To-do

- [ ] 인기 여행 일정 서버 연결
- [ ] 최신 여행 일정 서버 연결
- [ ] 에디터 추천 일정 서버 연결

## 📆 Date
220510
