### ISSUE TITLE
[REFECTOR] 구매 후 뷰 기능 합체 

### ISSUE THREAD

**Issue by shb03323** [TeamBeMyPlan/BeMyPlan-Android#26]
## 📝  To-do

- [x] noActionBar themes.xml로 연결
- [x] 구매후 뷰로 들어가는 임시 버튼 제거
- [x] 이름 리팩토링
- [x] 버튼 크기 조정
- [x] 버튼 리사이클러뷰로 설정

## 📆 Date

0112 ~ 0112
