### ISSUE TITLE
[FIX] QA 반영

### ISSUE THREAD

**Issue by hansh0101** [TeamBeMyPlan/BeMyPlan-Android#265]
## 📌  Feature Issue

[FIX] QA 반영

## 📝  To-do

- [x] 이미지 일부 안 나오는 문제
- [x] 홈탭에서 구매 전 여행 일정 미리보기 로딩 실패하는 문제
- [x] 홈탭 ViewPager2 `인기 여행 일정` 텍스트 수정

## 📆 Date

0517 ~ 0517
