### ISSUE TITLE
[FEAT] 마이플랜 - 큰 프래그먼트

### ISSUE THREAD

**Issue by shb03323** [TeamBeMyPlan/BeMyPlan-Android#32]
## 📝  To-do

- [x] 제목 삽입
- [x] 프로필 사진 삽입
- [x] 닉네임 삽입
- [x] 구매 개수 삽입
- [x] 설정 버튼 삽입

## 📆 Date

0112 ~ 0113
