### ISSUE TITLE
[FEAT] 구매한 여행 일정

### ISSUE THREAD

**Issue by shb03323** [TeamBeMyPlan/BeMyPlan-Android#35]
## 📝  To-do

- [x] 리사이클러뷰, 어댑터 설정
- [x] 데이터 클래스 생성
- [x] 데이터 바인딩
- [x] 그리드 레이아웃 설정

## 📆 Date

0113 ~ 0113
