### ISSUE TITLE
[CHORE] After Purchase 버튼 활성화

### ISSUE THREAD

**Issue by shb03323** [TeamBeMyPlan/BeMyPlan-Android#50]
## 📝  To-do

- [x] 뒤로가기 버튼 활성화
- [x] 일차 버튼 클릭 시 색 들어오도록 설정
- [x] 툴바 없애기
- [x] 복사 버튼 활성화
- [x] 일차 버튼 글씨 가운데 정렬
- [x] 스크롤 시 제목 툴바로 올리기

## 📆 Date

0115 ~ 0115
