### ISSUE TITLE
[FEAT] 디자인 수정사항 반영

### ISSUE THREAD

**Issue by hansh0101** [TeamBeMyPlan/BeMyPlan-Android#53]
## 📌  Feature Issue

[FEAT] 디자인 수정사항 반영

## 📝  To-do

- [x] 정렬 없어진 뷰 margin값 재조정
- [ ] 구매 전 여행일정 콘텐츠 세로 스크롤 -> 가로 스크롤 변경
- [ ] 구매 전 여행일정 콘텐츠 하단부 수정

## 📆 Date

0117~0117

**Comment by hansh0101** [comment]
구매 전 여행일정 콘텐츠 세로 스크롤로 유지하기로 결정되어 수정하지 않음

**Comment by hansh0101** [comment]
구매 전 여행일정 콘텐츠 하단부 수정사항 확정된 이후 작업 예정
