### ISSUE TITLE
[FEAT] 홈 뷰 인기여행일정 서버연결

### ISSUE THREAD

**Issue by briandr97** [TeamBeMyPlan/BeMyPlan-Android#64]
## 📌  Feature Issue
홈 뷰 인기여행일정 서버 연결

## 📝  To-do
- [x] 인기 여행 일정 데이터 바인딩
- [x] 인기 여행 일정 viewmodel 적용
- [x] 인기 여행 일정 서버 연결
- [ ] 결제 activity 내 fragment 생명 주기 수정

## 📆 Date
0118~0119

**Comment by briandr97** [comment]
하루 더 일찍 끝냈다! 다음껀 좀 더 빨리..
