### ISSUE TITLE
[FEAT] 여행지 뷰

### ISSUE THREAD

**Issue by briandr97** [TeamBeMyPlan/BeMyPlan-Android#73]
## 📌  Feature Issue
여행지 리스트 조회

## 📝  To-do
- [x] 여행지 데이터 바인딩
- [x] 여행지 viewmodel 적용
- [x] 여행지 서버 연결
- [x] 서버 boolean 값에 따라 잠김 필터 적용
- [ ] 결제 activity 내 fragment 생명 주기 수정

## 📆 Date
0118
