### ISSUE TITLE
[FEAT] 구매 후 뷰

### ISSUE THREAD

**Issue by shb03323** [TeamBeMyPlan/BeMyPlan-Android#9]
## 📝  To-do

- [x] 카카오맵 연동
- [x] 사진, 텍스트 추가
- [x] 이동 시간 박스 추가
- [x] 일차별 동선 그래프 추가
- [x] 일차별 버튼 추가
- [x] 제목 추가

## 📆 Date

0108~0110
