### ISSUE TITLE
[FEAT] 홈 뷰 최신 여행 일정 조회

### ISSUE THREAD

**Issue by briandr97** [TeamBeMyPlan/BeMyPlan-Android#94]
## 📌  Feature Issue
홈 뷰 최신 여행 일정 조회 서버 연결

## 📝  To-do
- [x] 최신 여행 일정 조회 데이터 바인딩
- [x] 최신 여행 일정 조회 viewmodel 적용
- [x] 최신 여행 일정 조회 서버 연결
- [x] 결제 activity 내 fragment 생명 주기 수정

## 📆 Date
0119~0120
